baseURL = "https://jrballot.github.io/"
title = "Júlio Ballot"
description = "This is my space"
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
gootnoteReturnLinkContents = "^"

#theme = "anatole"
theme = "hugo-theme-chunky-poster"
enableRobotsTXT = true
paginate = 2

[params]
  author = "Júlio Ballot"
  description = "... the advance of a non existent necessity"
#  profilePicture = "images/profile.jpg"
#  homepageImage = "images/external-content.duckduckgo.com.jpeg"
  favicon = "favicons/"

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
#[[params.socialIcons]]
#icon = "fa-linkedin"
#title = "LinkedIn"
#url = "https://www.linkedin.com/in/julioballot/"
#
#[[params.socialIcons]]
#icon = "fa-github"
#title = "GitHub"
#url = "https://github.com/jrballot"
#
#[[params.socialIcons]]
#icon = "fa-envelope"
#title = "e-mail"
#url = "mailto:julio.ballot@gmail.com"
[params.social]
  linkedin = "https://www.linkedin.com/in/julioballot/"
  github = "https://github.com/jrballot"
  email = "julio.ballot@gmail.com"

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 10
  url = "/"


  [[menu.main]]
  name = "Posts"
  weight = 0
  identifier = "posts"
  url = "/posts/"

  [[menu.main]]
  name = "About"
  weight = 0
  identifier = "about"
  url = "/about/"


[markup]
  [markup.highlight]
    style="tango"
    tabWidth=4
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
